server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/configdb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      server:
        jdbc:
          sql: "SELECT PROP_KEY, PROP_VALUE FROM PROPERTIES WHERE APPLICATION=? AND PROFILE=? AND LABEL=?"
          default-label: main

#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/pranayjumde0812/app-configuration-java-springboot
#          username: ${GIT_USER}
#          password: ${GIT_TOKEN}

#encrypt:
#  key: "0E329232EA6D0D73"

#  keytool -genkeypair -alias config-server-key -keyalg RSA -dname "CN=Config Server,OU=Spring Cloud,O=Company" -keypass mypass -keystore config-server.jks -storepass mypass

#  keytool -genkeypair \
#  -alias config-server-key \
#  -keyalg RSA \
#  -dname "CN=Config Server,OU=Spring Cloud,O=Company" \
#  -keypass mypass \
#  -keystore /home/admin1/JAVA/java-springboot-microservices/13-Configuration\ Management/config-server/src/main/resources/config-server.jks \
#  -storepass mypass

encrypt:
  key-store:
    location: config-server.jks
    password: mypass
    alias: config-server-key