spring:
  application:
    name: configdemo

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

  cloud:
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

