build:
  id: 20020
  version: 2.3.4
  name: "Native Prod-Production-Build"
  type: "Native Production"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
    endpoints:
      web:
        exposure:
          include: "*"